swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
host: localhost:8080
basePath: /
tags:
  - name: cliente-controller
    description: Cliente Controller
paths:
  /cliente:
    post:
      tags:
        - cliente-controller
      summary: guardarCliente
      operationId: guardarClienteUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: cliente
          description: cliente
          required: true
          schema:
            $ref: '#/definitions/Cliente'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Cliente'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  Cliente:
    type: object
    properties:
      apellidos:
        type: string
      dni:
        type: string
      email:
        type: string
      fecha_creacion:
        type: string
        format: date
      fecha_nacimiento:
        type: string
        format: date
      id:
        type: integer
        format: int32
      nombres:
        type: string
    title: Cliente
